import { DriverConnection, DriverProtocol } from '../../types';

export const PROTOCOL_LABELS: Record<DriverProtocol, string> = {
  opcua: 'OPC UA',
  opcda: 'OPC DA',
  modbus_tcp: 'Modbus TCP',
  modbus_rtu: 'Modbus RTU',
  iec61850: 'IEC 61850 (MMS / GOOSE)',
  s7: 'Siemens S7 (Snap7 / S7Comm)',
  melsec: 'Mitsubishi MELSEC (SLMP / MC)',
  ethernet_ip: 'EtherNet/IP (Rockwell / CIP)',
  profinet: 'PROFINET IO (Real-Time)',
  profibus: 'PROFIBUS DP (Fieldbus)',
  rs485: 'RS-485',
  rs232: 'RS-232',
  usb_serial: 'USB Serial',
  tcp_custom: 'TCP Custom',
  custom: 'Custom'
};

export const PROTOCOL_ICONS: Record<DriverProtocol, string> = {
  opcua: 'fa-sitemap',
  opcda: 'fa-sitemap',
  modbus_tcp: 'fa-network-wired',
  modbus_rtu: 'fa-microchip',
  iec61850: 'fa-bolt',
  s7: 'fa-industry',
  melsec: 'fa-microchip',
  ethernet_ip: 'fa-network-wired',
  profinet: 'fa-network-wired',
  profibus: 'fa-microchip',
  rs485: 'fa-wave-square',
  rs232: 'fa-microchip',
  usb_serial: 'fa-usb',
  tcp_custom: 'fa-plug',
  custom: 'fa-puzzle-piece'
};

export const createEmptyDriverConnection = (): Partial<DriverConnection> => ({
  connectionId: `drv_${Date.now()}`,
  connectionName: '',
  protocol: 'modbus_tcp',
  enabled: true,
  // PROFINET IO Defaults
  profinetStationName: 'io-device-1',
  profinetIp: '192.168.0.10',
  profinetSubnet: '255.255.255.0',
  profinetGateway: '192.168.0.1',
  profinetSendClockMs: 1,
  profinetReductionRatio: 1,
  // PROFIBUS DP Defaults
  profibusGatewayType: 'ie_pb_link',
  profibusNodeAddress: 3,
  profibusBaudRate: '1.5M',
  profibusIdentNumber: '0x8054',
  // EtherNet/IP (CIP) Defaults
  eipCpuType: 'compactlogix',
  cipSlot: 0,
  cipRoutePath: '1,0',
  cipSessionTimeoutMs: 10000,
  cipUseConnectedSockets: false,
  // Siemens S7 Defaults
  s7Model: 's7_1500',
  rack: 0,
  slot: 1,
  pduSize: 480,
  // Mitsubishi MELSEC Defaults
  melsecSeries: 'iq_f',
  melsecFrame: '3e_binary',
  networkNumber: 0,
  pcNumber: 255,
  destinationModuleIoNumber: 1023,
  destinationModuleStationNumber: 0,
  // IEC 61850 Substation Defaults
  iedName: 'IED1',
  apTitle: '1.1.1.999.1',
  aeQualifier: 12,
  mmsPort: 102,
  enableGoose: false,
  gooseInterface: 'eth0',
  gooseAppId: '0x0001',
  // OPC UA Defaults
  endpointUrl: 'opc.tcp://127.0.0.1:4840',
  secondaryEndpointUrl: '',
  overrideThumbprint: '',
  securityFallback: 'no_security',
  disableDomainCheck: false,
  browsingMode: 'browse_path',
  securityMode: 'None',
  securityPolicy: 'None',
  authMode: 'anonymous',
  username: '',
  password: '',
  userCertificateThumbprint: '',
  maxQueueSize: 1000,
  enableSubscription: true,
  subscriptionMode: 'read_attributes',
  readMaximumAgeMs: 1000,
  publishIntervalMs: 50,
  maxPointsPerBatch: 1000,
  browseMaxItemsAtATime: 200,
  workPeriodMs: 1000,
  logComplianceErrors: false,
  requestTimeoutMs: 10000,
  sessionTimeoutMs: 30000,
  connectTimeoutMs: 10000,
  // Modbus / Serial / TCP Defaults
  host: '127.0.0.1',
  port: 502,
  unitId: 1,
  timeout: 1000,
  sendTimeoutMs: 1000,
  recvTimeoutMs: 1000,
  sendRecvDelayMs: 0,
  frameRetryCount: 0,
  tcpSockets: 1,
  reopenSockets: false,
  zeroBasedAddressing: true,
  zeroBasedBitAddressing: true,
  byteSwap: false,
  wordSwap: false,
  dwordSwap: false,
  useSingleCoilWrite: true,
  useSingleRegisterWrite: true,
  retryInterval: 1000,
  portPath: 'COM1',
  baudRate: 9600,
  dataBits: 8,
  parity: 'none',
  stopBits: 1,
  flowControl: 'none',
  rtsToggle: false
});
